// Aqui é o layout padrão vindo da criação do projeto, onde estou importando o layoutconfig com as configurações de rota...
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import LayoutConfig from "@/components/Layout/layoutConfig";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LayoutRoot({children}: { children: ReactNode })
    {
        LayoutRoot = LayoutConfig
        return (
            <html>
            <body>
            <LayoutRoot>
                <div className={inter.className}>{children}</div>
            </LayoutRoot>
            </body>
            </html>
        )
    }
